<?php

namespace ContainerXGLO8t2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LtnXTc1Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.LtnXTc1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LtnXTc1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['privates', '.errored.wdRMn_8', NULL, 'Cannot determine controller argument for "App\\Controller\\CommentController::delete()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.ZqWEnH7', NULL, 'Cannot determine controller argument for "App\\Controller\\CommentController::delete()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
            'request' => '?',
        ]);
    }
}
