<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9SP5MUD\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9SP5MUD/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/Container9SP5MUD.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\Container9SP5MUD\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \Container9SP5MUD\App_KernelEnvDebugContainer([
    'container.build_hash' => '9SP5MUD',
    'container.build_id' => '264e17b1',
    'container.build_time' => 1672930130,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9SP5MUD');
