<?php

namespace Container9SP5MUD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UW5yRService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.u__W5yR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u__W5yR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ArticleController::create' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ArticleController::delete' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ArticleController::index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ArticleController::show' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ArticleController::update' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CategoryController::create' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CategoryController::update' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CommentController::create' => ['privates', '.service_locator.hJDDzeN', 'get_ServiceLocator_HJDDzeNService', true],
            'App\\Controller\\CommentController::delete' => ['privates', '.service_locator.LtnXTc1', 'get_ServiceLocator_LtnXTc1Service', true],
            'App\\Controller\\CommentController::update' => ['privates', '.service_locator.CLwTsPd', 'get_ServiceLocator_CLwTsPdService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\HomeController::list' => ['privates', '.service_locator.mU7E2aG', 'get_ServiceLocator_MU7E2aGService', true],
            'App\\Controller\\HomeController::show' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rRj.mG3', 'get_ServiceLocator_RRj_MG3Service', true],
            'App\\Controller\\RegistrationController::index' => ['privates', '.service_locator.paN13u7', 'get_ServiceLocator_PaN13u7Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rRj.mG3', 'get_ServiceLocator_RRj_MG3Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ArticleController:create' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ArticleController:delete' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ArticleController:index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ArticleController:show' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ArticleController:update' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CategoryController:create' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CategoryController:update' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\CommentController:create' => ['privates', '.service_locator.hJDDzeN', 'get_ServiceLocator_HJDDzeNService', true],
            'App\\Controller\\CommentController:delete' => ['privates', '.service_locator.LtnXTc1', 'get_ServiceLocator_LtnXTc1Service', true],
            'App\\Controller\\CommentController:update' => ['privates', '.service_locator.CLwTsPd', 'get_ServiceLocator_CLwTsPdService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\HomeController:list' => ['privates', '.service_locator.mU7E2aG', 'get_ServiceLocator_MU7E2aGService', true],
            'App\\Controller\\HomeController:show' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rRj.mG3', 'get_ServiceLocator_RRj_MG3Service', true],
            'App\\Controller\\RegistrationController:index' => ['privates', '.service_locator.paN13u7', 'get_ServiceLocator_PaN13u7Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rRj.mG3', 'get_ServiceLocator_RRj_MG3Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\ArticleController::create' => '?',
            'App\\Controller\\ArticleController::delete' => '?',
            'App\\Controller\\ArticleController::index' => '?',
            'App\\Controller\\ArticleController::show' => '?',
            'App\\Controller\\ArticleController::update' => '?',
            'App\\Controller\\CategoryController::create' => '?',
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::update' => '?',
            'App\\Controller\\CommentController::create' => '?',
            'App\\Controller\\CommentController::delete' => '?',
            'App\\Controller\\CommentController::update' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::list' => '?',
            'App\\Controller\\HomeController::show' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ArticleController:create' => '?',
            'App\\Controller\\ArticleController:delete' => '?',
            'App\\Controller\\ArticleController:index' => '?',
            'App\\Controller\\ArticleController:show' => '?',
            'App\\Controller\\ArticleController:update' => '?',
            'App\\Controller\\CategoryController:create' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:update' => '?',
            'App\\Controller\\CommentController:create' => '?',
            'App\\Controller\\CommentController:delete' => '?',
            'App\\Controller\\CommentController:update' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:list' => '?',
            'App\\Controller\\HomeController:show' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
