<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ3xElpI\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ3xElpI/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQ3xElpI.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQ3xElpI\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQ3xElpI\App_KernelProdContainer([
    'container.build_hash' => 'Q3xElpI',
    'container.build_id' => 'f6a2c7b7',
    'container.build_time' => 1672931625,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ3xElpI');
