<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAfRox0x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAfRox0x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAfRox0x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAfRox0x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAfRox0x\App_KernelDevDebugContainer([
    'container.build_hash' => 'AfRox0x',
    'container.build_id' => 'd2892e29',
    'container.build_time' => 1672858037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAfRox0x');
